/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hospitalmanagement;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import java.util.HashMap;

/**
 *
 * @author haris
 */
public class Email extends javax.swing.JPanel {

   
    public final LineBorder HOVER_BTN_BORDER = new LineBorder(new Color(0x7C7CF1), 2, true);
    public final LineBorder DEFAULT_BTN_BORDER = new LineBorder(Color.WHITE, 1, true);
    public final LineBorder DEFAULT_BORDER = new LineBorder(Color.blue, 1, true);
    public final LineBorder INPUT_BORDER = new LineBorder(new Color(0x7c7cf1), 1, true);
    public final LineBorder HOVER_BORDER = new LineBorder(new Color(0x7C7CF1), 2, true);
    public final LineBorder WARNING_BORDER = new LineBorder(new Color(0xff3333), 2, true);

    public final Color WARNING_COLOR = new Color(16724787);
    public final Color SUCCESS_COLOR = new Color(0, 153, 0);
    public final Color CLICKED_LABEL_COLOR = new Color(0, 0, 204);
    public final Color REPORT_LABEL_COLOR = new Color(0, 0, 102);
     CardLayout card;
    public Email() {
        initComponents();
         showEmailTypePage("email_mode");
    }
    public void showEmailTypePage(String page_name) {
        card = (CardLayout) modes.getLayout();
        card.show(modes, page_name);
        

        HashMap<String, JLabel> mp = new HashMap<String, JLabel>(); 
        mp.put("email_mode", custome_email_label);
        mp.put("patient_mode", patient_details_email_label);
        mp.put("add_email", add_email_label);
        JLabel menu_panel_label_list[] = {custome_email_label, patient_details_email_label, add_email_label};

       
       // mp.get(page_name).setForeground(Color.CYAN);
        for (JLabel menu_panel_label_list1 : menu_panel_label_list) {
            if (menu_panel_label_list1 == mp.get(page_name)) {
                menu_panel_label_list1.setForeground(Color.BLUE);
                menu_panel_label_list1.setBackground(new Color(205, 207, 185));
               
            } else {
                menu_panel_label_list1.setForeground(Color.black);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_panel_head = new javax.swing.JPanel();
        patient_panel_header_title2 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        main_panel = new javax.swing.JPanel();
        email_sending_panel = new javax.swing.JPanel();
        modes = new javax.swing.JPanel();
        patient_details_mode = new javax.swing.JPanel();
        from_email_input3 = new javax.swing.JTextField();
        medicine_input = new javax.swing.JTextField();
        add_medicine_btn = new javax.swing.JButton();
        medicine_list_panel = new javax.swing.JPanel();
        medicine_list = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        from_email_input4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        add_medicine_btn1 = new javax.swing.JButton();
        add_medicine_btn2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        add_medicine_btn3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        email_mode = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        from_email_input1 = new javax.swing.JTextField();
        from_email_input2 = new javax.swing.JTextField();
        add_email_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        from_email_input5 = new javax.swing.JTextField();
        from_email_input6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        custome_email_label = new javax.swing.JLabel();
        patient_details_email_label = new javax.swing.JLabel();
        update_from_email_btn = new javax.swing.JButton();
        from_email_label = new javax.swing.JLabel();
        from_email_input = new javax.swing.JTextField();
        add_email_label = new javax.swing.JLabel();
        composing_email_panel = new javax.swing.JPanel();
        upper_pannel_for_margin = new javax.swing.JPanel();
        left_pannel_for_margin = new javax.swing.JPanel();
        down_pannel_for_margin = new javax.swing.JPanel();
        right_pannel_for_margin = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        email_panel_head.setBackground(new java.awt.Color(0, 0, 102));
        email_panel_head.setForeground(new java.awt.Color(51, 255, 255));
        email_panel_head.setMinimumSize(new java.awt.Dimension(169, 40));
        email_panel_head.setPreferredSize(new java.awt.Dimension(169, 35));

        patient_panel_header_title2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        patient_panel_header_title2.setForeground(new java.awt.Color(102, 255, 255));
        patient_panel_header_title2.setText("Email");
        email_panel_head.add(patient_panel_header_title2);

        add(email_panel_head, java.awt.BorderLayout.PAGE_START);

        content_panel.setBackground(new java.awt.Color(204, 255, 255));
        content_panel.setLayout(new java.awt.BorderLayout());

        main_panel.setBackground(new java.awt.Color(204, 255, 255));
        main_panel.setLayout(new java.awt.BorderLayout(3, 0));

        email_sending_panel.setBackground(new java.awt.Color(251, 252, 224));
        email_sending_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));
        email_sending_panel.setPreferredSize(new java.awt.Dimension(600, 100));

        modes.setLayout(new java.awt.CardLayout());

        patient_details_mode.setBackground(new java.awt.Color(239, 240, 209));
        patient_details_mode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        from_email_input3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input3MouseExited(evt);
            }
        });
        from_email_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input3ActionPerformed(evt);
            }
        });

        medicine_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medicine_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medicine_inputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medicine_inputMouseExited(evt);
            }
        });
        medicine_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                medicine_inputKeyPressed(evt);
            }
        });

        add_medicine_btn.setBackground(new java.awt.Color(0, 51, 255));
        add_medicine_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_medicine_btn.setText("Add");
        add_medicine_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        add_medicine_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_medicine_btn.setFocusPainted(false);
        add_medicine_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_medicine_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_medicine_btnMouseExited(evt);
            }
        });
        add_medicine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_btnActionPerformed(evt);
            }
        });

        medicine_list_panel.setPreferredSize(new java.awt.Dimension(0, 240));
        medicine_list_panel.setLayout(new java.awt.CardLayout());

        medicine_list.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        medicine_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        medicine_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicine_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicine_listMouseClicked(evt);
            }
        });
        medicine_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                medicine_listKeyPressed(evt);
            }
        });
        medicine_list_panel.add(medicine_list, "card2");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Patient Email :");
        jLabel11.setPreferredSize(new java.awt.Dimension(38, 28));

        from_email_input4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input4MouseExited(evt);
            }
        });
        from_email_input4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Subject:-");

        jLabel13.setText("Body:-");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add_medicine_btn1.setBackground(new java.awt.Color(0, 51, 255));
        add_medicine_btn1.setForeground(new java.awt.Color(255, 255, 255));
        add_medicine_btn1.setText("Save");
        add_medicine_btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        add_medicine_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_medicine_btn1.setFocusPainted(false);
        add_medicine_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_medicine_btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_medicine_btn1MouseExited(evt);
            }
        });
        add_medicine_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_btn1ActionPerformed(evt);
            }
        });

        add_medicine_btn2.setBackground(new java.awt.Color(0, 51, 255));
        add_medicine_btn2.setForeground(new java.awt.Color(255, 255, 255));
        add_medicine_btn2.setText("Send");
        add_medicine_btn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        add_medicine_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_medicine_btn2.setFocusPainted(false);
        add_medicine_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_medicine_btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_medicine_btn2MouseExited(evt);
            }
        });
        add_medicine_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_btn2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Attach:-");

        add_medicine_btn3.setBackground(new java.awt.Color(0, 51, 255));
        add_medicine_btn3.setForeground(new java.awt.Color(255, 255, 255));
        add_medicine_btn3.setText("Add File");
        add_medicine_btn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        add_medicine_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_medicine_btn3.setFocusPainted(false);
        add_medicine_btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_medicine_btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_medicine_btn3MouseExited(evt);
            }
        });
        add_medicine_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_btn3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Enter Patient Name :-");

        javax.swing.GroupLayout patient_details_modeLayout = new javax.swing.GroupLayout(patient_details_mode);
        patient_details_mode.setLayout(patient_details_modeLayout);
        patient_details_modeLayout.setHorizontalGroup(
            patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_details_modeLayout.createSequentialGroup()
                .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patient_details_modeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(patient_details_modeLayout.createSequentialGroup()
                                .addComponent(medicine_input, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_medicine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(from_email_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(patient_details_modeLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(from_email_input4)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                    .addGroup(patient_details_modeLayout.createSequentialGroup()
                        .addComponent(add_medicine_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(add_medicine_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_medicine_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(patient_details_modeLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(medicine_list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        patient_details_modeLayout.setVerticalGroup(
            patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_details_modeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patient_details_modeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from_email_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patient_details_modeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addGroup(patient_details_modeLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(add_medicine_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicine_input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(patient_details_modeLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from_email_input4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_medicine_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_medicine_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(add_medicine_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(patient_details_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(patient_details_modeLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(medicine_list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        modes.add(patient_details_mode, "patient_mode");

        email_mode.setBackground(new java.awt.Color(239, 240, 209));
        email_mode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jLabel3.setText("To:- ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Subject :-");
        jLabel1.setPreferredSize(new java.awt.Dimension(38, 28));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Body :-");
        jLabel7.setPreferredSize(new java.awt.Dimension(38, 28));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Send");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Save");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Attach :-");

        jButton4.setBackground(new java.awt.Color(0, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add File");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        from_email_input1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input1MouseExited(evt);
            }
        });
        from_email_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input1ActionPerformed(evt);
            }
        });

        from_email_input2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input2MouseExited(evt);
            }
        });
        from_email_input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout email_modeLayout = new javax.swing.GroupLayout(email_mode);
        email_mode.setLayout(email_modeLayout);
        email_modeLayout.setHorizontalGroup(
            email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_modeLayout.createSequentialGroup()
                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(email_modeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(email_modeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(email_modeLayout.createSequentialGroup()
                                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(from_email_input2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(from_email_input1)))))
                    .addGroup(email_modeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        email_modeLayout.setVerticalGroup(
            email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_modeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from_email_input2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from_email_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(email_modeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        modes.add(email_mode, "email_mode");

        add_email_panel.setBackground(new java.awt.Color(239, 240, 209));
        add_email_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Subject :-");
        jLabel2.setPreferredSize(new java.awt.Dimension(38, 28));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Template Name :-");
        jLabel4.setPreferredSize(new java.awt.Dimension(38, 28));

        from_email_input5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input5MouseExited(evt);
            }
        });
        from_email_input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input5ActionPerformed(evt);
            }
        });

        from_email_input6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_input6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_input6MouseExited(evt);
            }
        });
        from_email_input6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_input6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Body:-");
        jLabel5.setPreferredSize(new java.awt.Dimension(38, 28));

        jLabel9.setText("Attach :-");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButton5.setBackground(new java.awt.Color(0, 51, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add File");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 51, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Save");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_email_panelLayout = new javax.swing.GroupLayout(add_email_panel);
        add_email_panel.setLayout(add_email_panelLayout);
        add_email_panelLayout.setHorizontalGroup(
            add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_email_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(add_email_panelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_email_panelLayout.createSequentialGroup()
                        .addComponent(from_email_input6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_email_panelLayout.createSequentialGroup()
                        .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(add_email_panelLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addComponent(from_email_input5))
                        .addGap(73, 73, 73))))
        );
        add_email_panelLayout.setVerticalGroup(
            add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_email_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_email_input6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_email_input5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(add_email_panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(add_email_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)
                        .addGroup(add_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );

        modes.add(add_email_panel, "add_email");

        custome_email_label.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        custome_email_label.setText("Custom Email");
        custome_email_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custome_email_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custome_email_labelMouseClicked(evt);
            }
        });

        patient_details_email_label.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        patient_details_email_label.setText("Patient Details");
        patient_details_email_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient_details_email_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_details_email_labelMouseClicked(evt);
            }
        });

        update_from_email_btn.setBackground(new java.awt.Color(0, 51, 255));
        update_from_email_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_from_email_btn.setText("Update");
        update_from_email_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        update_from_email_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_from_email_btnActionPerformed(evt);
            }
        });

        from_email_label.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        from_email_label.setText("From : ");
        from_email_label.setPreferredSize(new java.awt.Dimension(38, 28));

        from_email_input.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        from_email_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 124, 241), 1, true));
        from_email_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                from_email_inputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                from_email_inputMouseExited(evt);
            }
        });
        from_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_email_inputActionPerformed(evt);
            }
        });

        add_email_label.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 14)); // NOI18N
        add_email_label.setText("Add Email");
        add_email_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_email_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_email_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout email_sending_panelLayout = new javax.swing.GroupLayout(email_sending_panel);
        email_sending_panel.setLayout(email_sending_panelLayout);
        email_sending_panelLayout.setHorizontalGroup(
            email_sending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_sending_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(email_sending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(email_sending_panelLayout.createSequentialGroup()
                        .addComponent(custome_email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patient_details_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(email_sending_panelLayout.createSequentialGroup()
                        .addComponent(from_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_from_email_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(modes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        email_sending_panelLayout.setVerticalGroup(
            email_sending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_sending_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(email_sending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_from_email_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_email_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(from_email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(email_sending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_email_label)
                    .addComponent(patient_details_email_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custome_email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(modes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.add(email_sending_panel, java.awt.BorderLayout.CENTER);

        composing_email_panel.setBackground(new java.awt.Color(251, 252, 224));
        composing_email_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 1, true));
        composing_email_panel.setPreferredSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout composing_email_panelLayout = new javax.swing.GroupLayout(composing_email_panel);
        composing_email_panel.setLayout(composing_email_panelLayout);
        composing_email_panelLayout.setHorizontalGroup(
            composing_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        composing_email_panelLayout.setVerticalGroup(
            composing_email_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        main_panel.add(composing_email_panel, java.awt.BorderLayout.LINE_END);

        content_panel.add(main_panel, java.awt.BorderLayout.CENTER);

        upper_pannel_for_margin.setBackground(new java.awt.Color(204, 255, 255));
        upper_pannel_for_margin.setPreferredSize(new java.awt.Dimension(800, 8));
        content_panel.add(upper_pannel_for_margin, java.awt.BorderLayout.PAGE_START);

        left_pannel_for_margin.setBackground(new java.awt.Color(204, 255, 255));
        left_pannel_for_margin.setPreferredSize(new java.awt.Dimension(10, 400));
        content_panel.add(left_pannel_for_margin, java.awt.BorderLayout.LINE_START);

        down_pannel_for_margin.setBackground(new java.awt.Color(204, 255, 255));
        down_pannel_for_margin.setPreferredSize(new java.awt.Dimension(800, 8));
        content_panel.add(down_pannel_for_margin, java.awt.BorderLayout.PAGE_END);

        right_pannel_for_margin.setBackground(new java.awt.Color(204, 255, 255));
        right_pannel_for_margin.setPreferredSize(new java.awt.Dimension(10, 400));
        content_panel.add(right_pannel_for_margin, java.awt.BorderLayout.LINE_END);

        add(content_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void update_from_email_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_from_email_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_from_email_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void from_email_inputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_inputMouseEntered
        if (from_email_input.getBorder() != WARNING_BORDER) {
            from_email_input.setBorder(HOVER_BORDER);
        }
    }//GEN-LAST:event_from_email_inputMouseEntered

    private void from_email_inputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_inputMouseExited
        if (from_email_input.getBorder() != WARNING_BORDER) {
            from_email_input.setBorder(INPUT_BORDER);
        }
    }//GEN-LAST:event_from_email_inputMouseExited

    private void from_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_inputActionPerformed

    private void from_email_input1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input1MouseEntered

    private void from_email_input1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input1MouseExited

    private void from_email_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input1ActionPerformed

    private void from_email_input2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input2MouseEntered

    private void from_email_input2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input2MouseExited

    private void from_email_input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input2ActionPerformed

    private void from_email_input3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input3MouseEntered

    private void from_email_input3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input3MouseExited

    private void from_email_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input3ActionPerformed

    private void medicine_inputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicine_inputMouseEntered
        medicine_input.setBorder(HOVER_BORDER);
    }//GEN-LAST:event_medicine_inputMouseEntered

    private void medicine_inputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicine_inputMouseExited
        medicine_input.setBorder(INPUT_BORDER);
    }//GEN-LAST:event_medicine_inputMouseExited

    private void medicine_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicine_inputKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addMedicine();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            medicine_list.grabFocus();
            medicine_list.setSelectedIndex(0);

        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {

            if (medicine_list.getSelectedIndex() == 0) {
                medicine_input.grabFocus();
            } else {
                medicine_list.grabFocus();
            }

        }
    }//GEN-LAST:event_medicine_inputKeyPressed

    private void add_medicine_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btnMouseEntered
        add_medicine_btn.setBorder(HOVER_BTN_BORDER);
    }//GEN-LAST:event_add_medicine_btnMouseEntered

    private void add_medicine_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btnMouseExited
        add_medicine_btn.setBorder(DEFAULT_BTN_BORDER);
    }//GEN-LAST:event_add_medicine_btnMouseExited

    private void add_medicine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_btnActionPerformed
        addMedicine();
    }//GEN-LAST:event_add_medicine_btnActionPerformed

    private void from_email_input4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input4MouseEntered

    private void from_email_input4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input4MouseExited

    private void from_email_input4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input4ActionPerformed

    private void add_medicine_btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn1MouseEntered

    private void add_medicine_btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn1MouseExited

    private void add_medicine_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn1ActionPerformed

    private void add_medicine_btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn2MouseEntered

    private void add_medicine_btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn2MouseExited

    private void add_medicine_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn2ActionPerformed

    private void add_medicine_btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn3MouseEntered

    private void add_medicine_btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_medicine_btn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn3MouseExited

    private void add_medicine_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_medicine_btn3ActionPerformed

    private void medicine_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicine_listKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addMedicine();
            medicine_input.grabFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_UP) {

            if (medicine_list.getSelectedIndex() == 0) {
                medicine_input.grabFocus();
            } else {
                medicine_list.grabFocus();
            }

        }
    }//GEN-LAST:event_medicine_listKeyPressed

    private void medicine_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicine_listMouseClicked

        if (evt.getClickCount() == 1) {

            addMedicine();
            //resetMedicineInputList();
            medicine_input.grabFocus();
            evt.consume();
        }
        //medicine_input.setText(medicine_list.getSelectedValue());
    }//GEN-LAST:event_medicine_listMouseClicked

    private void custome_email_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custome_email_labelMouseClicked
        showEmailTypePage("email_mode");
    }//GEN-LAST:event_custome_email_labelMouseClicked

    private void patient_details_email_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_details_email_labelMouseClicked
         showEmailTypePage("patient_mode");
    }//GEN-LAST:event_patient_details_email_labelMouseClicked

    private void add_email_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_email_labelMouseClicked
         showEmailTypePage("add_email");
    }//GEN-LAST:event_add_email_labelMouseClicked

    private void from_email_input5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input5MouseEntered

    private void from_email_input5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input5MouseExited

    private void from_email_input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input5ActionPerformed

    private void from_email_input6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input6MouseEntered

    private void from_email_input6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_from_email_input6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input6MouseExited

    private void from_email_input6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_email_input6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_email_input6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_email_label;
    private javax.swing.JPanel add_email_panel;
    private javax.swing.JButton add_medicine_btn;
    private javax.swing.JButton add_medicine_btn1;
    private javax.swing.JButton add_medicine_btn2;
    private javax.swing.JButton add_medicine_btn3;
    private javax.swing.JPanel composing_email_panel;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel custome_email_label;
    private javax.swing.JPanel down_pannel_for_margin;
    private javax.swing.JPanel email_mode;
    private javax.swing.JPanel email_panel_head;
    private javax.swing.JPanel email_sending_panel;
    private javax.swing.JTextField from_email_input;
    private javax.swing.JTextField from_email_input1;
    private javax.swing.JTextField from_email_input2;
    private javax.swing.JTextField from_email_input3;
    private javax.swing.JTextField from_email_input4;
    private javax.swing.JTextField from_email_input5;
    private javax.swing.JTextField from_email_input6;
    private javax.swing.JLabel from_email_label;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel left_pannel_for_margin;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField medicine_input;
    private javax.swing.JList<String> medicine_list;
    private javax.swing.JPanel medicine_list_panel;
    private javax.swing.JPanel modes;
    private javax.swing.JLabel patient_details_email_label;
    private javax.swing.JPanel patient_details_mode;
    private javax.swing.JLabel patient_panel_header_title2;
    private javax.swing.JPanel right_pannel_for_margin;
    private javax.swing.JButton update_from_email_btn;
    private javax.swing.JPanel upper_pannel_for_margin;
    // End of variables declaration//GEN-END:variables

    private void addMedicine() {
    }
}
