package pages;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;
import database.PDFDatabase;
import hospitalmanagement.Home;
import java.awt.HeadlessException;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import myutil.SetImageIcon;

/**
 *
 * @author haris
 */
public class DocumentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookmarkPanel
     */
    Home home;
    String next_page_icon = "./images/right_arrow.png";
    String refresh_page_icon = "./images/refresh3.png";
    DefaultListModel list_model = new DefaultListModel();
    HashMap<File, String> selected_files = new HashMap<>();
    // List<mp> selected_files = new LinkedList<>();

    public DocumentsPanel(JFrame home) {
        initComponents();

        this.home = (Home) home;

        next.add(new SetImageIcon(new ImageIcon(next_page_icon), 25, 25), BorderLayout.CENTER);
        document_refresh.add(new SetImageIcon(new ImageIcon(refresh_page_icon), 30, 30), BorderLayout.CENTER);
        document_list_panel.add(new JScrollPane(document_list));

      
    }

    public JList<String> getDocumentList() {
        return this.document_list;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        documnet_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        documnet_input = new javax.swing.JTextField();
        document_list_panel = new javax.swing.JPanel();
        document_list = new javax.swing.JList<>();
        add_document_btn = new javax.swing.JButton();
        document_delete_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        document_status_label = new javax.swing.JLabel();
        document_refresh = new javax.swing.JPanel();
        next = new javax.swing.JPanel();

        setBackground(new java.awt.Color(251, 252, 224));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPreferredSize(new java.awt.Dimension(200, 528));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(251, 252, 224));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        documnet_panel.setBackground(new java.awt.Color(251, 252, 224));
        documnet_panel.setAutoscrolls(true);
        documnet_panel.setPreferredSize(new java.awt.Dimension(300, 528));

        jLabel7.setText("Documents");

        documnet_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documnet_inputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documnet_inputMouseExited(evt);
            }
        });

        document_list_panel.setLayout(new java.awt.CardLayout());

        document_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        document_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        document_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                document_listMouseClicked(evt);
            }
        });
        document_list_panel.add(document_list, "card2");

        add_document_btn.setBackground(new java.awt.Color(0, 51, 255));
        add_document_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_document_btn.setText("Add");
        add_document_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_document_btn.setFocusPainted(false);
        add_document_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_document_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_document_btnMouseExited(evt);
            }
        });
        add_document_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_document_btnActionPerformed(evt);
            }
        });

        document_delete_btn.setBackground(new java.awt.Color(255, 51, 51));
        document_delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        document_delete_btn.setText("Delete");
        document_delete_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        document_delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        document_delete_btn.setFocusPainted(false);
        document_delete_btn.setPreferredSize(new java.awt.Dimension(27, 18));
        document_delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                document_delete_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                document_delete_btnMouseExited(evt);
            }
        });
        document_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                document_delete_btnActionPerformed(evt);
            }
        });

        jLabel16.setText("Document Name :-");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        document_refresh.setBackground(new java.awt.Color(251, 252, 224));
        document_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        document_refresh.setPreferredSize(new java.awt.Dimension(30, 30));
        document_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                document_refreshMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                document_refreshMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                document_refreshMouseReleased(evt);
            }
        });
        document_refresh.setLayout(new java.awt.BorderLayout());

        next.setBackground(new java.awt.Color(251, 252, 224));
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.setPreferredSize(new java.awt.Dimension(25, 25));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextMouseReleased(evt);
            }
        });
        next.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout documnet_panelLayout = new javax.swing.GroupLayout(documnet_panel);
        documnet_panel.setLayout(documnet_panelLayout);
        documnet_panelLayout.setHorizontalGroup(
            documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documnet_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(documnet_panelLayout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel16)
                        .addGroup(documnet_panelLayout.createSequentialGroup()
                            .addComponent(documnet_input, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(add_document_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator3)
                        .addComponent(document_delete_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(document_list_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(jSeparator4)
                        .addComponent(document_status_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(documnet_panelLayout.createSequentialGroup()
                        .addComponent(document_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        documnet_panelLayout.setVerticalGroup(
            documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documnet_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documnet_input, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_document_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(document_list_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(document_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(document_status_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(documnet_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(document_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(documnet_panel);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void add_document_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_document_btnActionPerformed

        //get the file from file chooser 
        //insert it into document list
        try {
            JFileChooser file_chooser = new JFileChooser();
            file_chooser.showOpenDialog(null);
            File file = file_chooser.getSelectedFile();

            if (file != null) {
                list_model.addElement(file.getName());
                String document_name = documnet_input.getText();
                if (document_name.length() == 0) {
                    document_name = file.getName().split("\\.")[0];
                }

                selected_files.put(file, document_name);

                document_list.setModel(list_model);

                documnet_input.setText("");

                revalidate();
                repaint();
            }

        } catch (HeadlessException exp) {
        }

    }//GEN-LAST:event_add_document_btnActionPerformed
    public void saveFilesFor(int patient_id) {
        PDFDatabase pdf_db = new PDFDatabase();
        for (Map.Entry<File, String> map : selected_files.entrySet()) {
            File file = map.getKey();
            String file_ref_name = map.getValue();

            pdf_db.storePdf(file_ref_name, file, patient_id);
        }
    }
    private void document_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_document_delete_btnActionPerformed

        try {

            int index = document_list.getSelectedIndex();

            
            for(Map.Entry<File,String> mp : selected_files.entrySet())
            {
                File file = mp.getKey();
                if(file.getName().equals(list_model.get(index))){
                    selected_files.remove(file);
                    break;
                }
            }
            
            list_model.remove(index);

            document_status_label.setText("Document Removed Successfuly.");
            document_status_label.setForeground(home.SUCCESS_COLOR);
            validate();
            repaint();
        } catch (Exception exp) {
            System.out.println(exp.getMessage());
            document_status_label.setText("Unable to remove bookmark");
            document_status_label.setForeground(home.WARNING_COLOR);
        }
    }//GEN-LAST:event_document_delete_btnActionPerformed

    private void documnet_inputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documnet_inputMouseEntered
        documnet_input.setBorder(home.HOVER_BORDER);
    }//GEN-LAST:event_documnet_inputMouseEntered

    private void add_document_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_document_btnMouseEntered
        add_document_btn.setBorder(home.HOVER_BTN_BORDER);
    }

    private void add_medicine_btnMouseExited(java.awt.event.MouseEvent evt) {
        add_document_btn.setBorder(home.DEFAULT_BTN_BORDER);
    }//GEN-LAST:event_add_document_btnMouseEntered

    private void documnet_inputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documnet_inputMouseExited
        documnet_input.setBorder(home.INPUT_BORDER);
    }//GEN-LAST:event_documnet_inputMouseExited

    private void add_document_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_document_btnMouseExited
        add_document_btn.setBorder(home.DEFAULT_BTN_BORDER);
    }//GEN-LAST:event_add_document_btnMouseExited

    private void document_delete_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_delete_btnMouseEntered
        document_delete_btn.setBorder(home.DEFAULT_BTN_BORDER);
    }//GEN-LAST:event_document_delete_btnMouseEntered

    private void document_delete_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_delete_btnMouseExited
        document_delete_btn.setBorder(new LineBorder(new Color(10066329), 1, true));
    }//GEN-LAST:event_document_delete_btnMouseExited

    private void document_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_listMouseClicked

    }//GEN-LAST:event_document_listMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked

        if (home.getHomeUser().getUserType().equals("Compounder")) {
            home.showPageOnWindow("reports");
        } else {
            home.showPageOnWindow("prescription");
        }

    }//GEN-LAST:event_nextMouseClicked

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nextMouseExited

    private void nextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nextMouseReleased

    private void document_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_refreshMouseClicked
         resetDocumentPage();
    }//GEN-LAST:event_document_refreshMouseClicked

    private void document_refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_refreshMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_document_refreshMouseExited

    private void document_refreshMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_document_refreshMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_document_refreshMouseReleased

    public void resetDocumentPage() {
        documnet_input.setText("");
        // new_bookmark_input.setText("");
        document_status_label.setText("");
//        DefaultListModel lm = (DefaultListModel) document_list.getModel();
        list_model.removeAllElements();

        selected_files.clear();
        document_list.removeAll();

        validate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_document_btn;
    private javax.swing.JButton document_delete_btn;
    private javax.swing.JList<String> document_list;
    private javax.swing.JPanel document_list_panel;
    private javax.swing.JPanel document_refresh;
    private javax.swing.JLabel document_status_label;
    private javax.swing.JTextField documnet_input;
    private javax.swing.JPanel documnet_panel;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel next;
    // End of variables declaration//GEN-END:variables
}
